/*
 * This source file was generated by the Gradle 'init' task
 */

#include "app.h"
#include <cassert>
#include <iostream>

int main() {
    VirtualDockingSoftware::Greeter greeter;
    assert(greeter.greeting().compare("Hello, World!") == 0);
    return 0;
}
