cc_library(
    name = "libusb",
    srcs = glob(["libusb/*.c"]),
    hdrs = glob(["libusb/*.h"]),
    includes = ["libusb", "."],
    visibility = ["//visibility:public"],
    copts = ["-Iexternal/libusb/libusb", "-Iexternal/libusb"]
)

