load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "libusb",
    urls = ["https://github.com/libusb/libusb/archive/refs/tags/v1.0.24.tar.gz"],
    build_file = "//app:libusb.BUILD",
    strip_prefix = "libusb-1.0.24",
)