name: Bazel Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Bazel
        uses: bazelbuild/setup-bazelisk@v3
      - name: Change Directory
        shell: bash
        run: |-
          cd app
      - name: Build with Bazel
        run: bazel build //main:hello-world
      - name: Test with Bazel
        run: bazel test //main:hello-world
